### ISSUE TITLE
web accessibility statement in footer

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_base#10]
[page.html.twig](https://github.com/CU-CommunityApps/cwd_base/blob/master/templates/page.html.twig)

Put the full a11y statement in the footer -- instead of just the contact email -- right...?

**Comment by alisonjo315** [comment]
So here's the code on FCS -- idk if there's a more current version or what 🤷‍♀ 

```html
<div class="content footer-accessibility vertical-align">
  <p>If you have a disability and are having trouble accessing information on this website or need materials in an alternate format, contact <a href="mailto:web-accessibility@cornell.edu">web-accessibility@cornell.edu</a> for assistance.</p>
</div>
```

**Comment by alisonjo315** [comment]
@ama39 @woodseowl 

So like, presumably could replace the (inner-)contents of `div.primary` with the HTML in my prior comment on this thread -- or a newer version if there's a newer version.

Objections / concerns?  If not, I can make the change and create a PR.  (Obviously not an emergency situation.)

**Comment by ama39** [comment]
Adding the newer WA message makes sense to me. There's a modest bit of supporting CSS that was in FCS and other recent child themes, but wasn't in the base stylesheet for a while. But it looks like I added it to the base stylesheet at some point, so it should work. If it does, you'll see an icon at desktop sizes, and vertical alignment for one or multiple lines (like in FCS). Go for it!

**Comment by woodseowl** [comment]
The solution that I create for this on Migrations and SCL was to push the accessibility content (and a few other standard footer elements) into blocks with hard-coded templates so that the page.html.twig file isn't managing it. This component-ized solution is something I'd like to push back to CD Demo / cwd_base, and the intent is the same as what you've got here. I have hours scheduled to work on this in December.

**Comment by alisonjo315** [comment]
Custom block entities, or, what kind of blocks do you mean?

Components == awesome, but why not use partial templates that get included in "host templates"?

**Comment by woodseowl** [comment]
Yes, custom block entity at the moment. (I've wondered if it would be better if it was module-based, but haven't considered the overhead compared to our clone-deploy approach.)

I'd love some feedback on the solution once I can show it to you and have time to describe the problems I was solving that led to those choices. Briefly: I used blocks instead of partial templates in Migrations because I found that I was having less conflicting models of layout with everything using regions and block management. It kept me from needing different page.html.twig files or needing to have conditional logic there. But I think I took this model to the Accessibility chunk simply because other elements were using it.

Happy to demo and discuss, perhaps with a PR when I work on this?

**Comment by alisonjo315** [comment]
Gotcha, cool beans -- yeah let's do that!

**Comment by alisonjo315** [comment]
Oh here it is! cc @ama39

**Comment by woodseowl** [comment]
And now I remember the problem to solve... how to get it in the right region. That's why I dropped in in a block. I'll see what I can do this afternoon.

**Comment by alisonjo315** [comment]
"Fixed" (or however you want to think about it) in last month's [1.0.5 tag](https://github.com/CU-CommunityApps/cwd_base/releases/tag/1.0.5) ([direct link](https://github.com/CU-CommunityApps/cwd_base/commit/6a31e4aa7b6fcc851a1d01cdcd10a04bb2f23dd1#diff-5d225d2e3e8538dcc0aa6138eae8454a)).
